#!/usr/bin/env bash
# Creates a file that contains its PID and handles various signals

sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap "echo Y U no love me?!; exit" SIGINT
trap 'sudo rm /var/run/holbertonscript.pid; echo "I hate the kill command"; exit' SIGQUIT SIGTERM
while true; do
 echo "To infinity and beyond"
done
