#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times with until loop

i=0
while [ $i -lt 11 ]; do
        if [ $i -eq 9 ]
        then
                echo "Hi"
        else
                echo "Holberton School"
        fi
        ((i = i + 1))
done
