#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
list="$(ls -1)"

for i in $list; do
        echo "$i" | cut --complement -d "-" -f1
done
